"glass_width" = 152
"glass_height"= 101
"glass_thickness"= 2.5
"brood_space"= 42
"t1"= 6
"t2"= 3.2
"D1@Sketch1"="glass_width"+"t1"+"t1"
"box_depth"= "brood_space" + "glass_thickness" + "glass_thickness" + "t2" + "t2"
"box_width"= "glass_width" + "t1" + "t1"
"food_height"= 70
"box_height" = "glass_height" + ( "t1" * 3 ) + "food_height"